* Basics
"M" means ALT key. "C" means CTRL key.

For example, "M-x" means pressing ALT and X key together in Emacs.

Download https://github.com/redguardtoo/hello/archive/master.zip and extracted somewhere, say "~/hello/". It contains sample code files written in different programming languages.

By default, I use vim key bindings. You can "C-z" to toggle into Emacs key bindings.

Error message is always dumped into "\*Messages\*" buffer. You can "C-x C-b" to select buffer named "\*Messages\*" in order to get the error message.

BTW, README at https://github.com/redguardtoo/emacs.d has all the technical information you need.

* Get the Emacs version
In bash shell, run comand,
#+BEGIN_SRC sh
emacs --version
#+END_SRC

* Start up
In bash shell, run command,
#+BEGIN_SRC sh
emacs -nw  --debug-init
#+END_SRC

Please "M-x toggle debug-on-error" after startup.
* Test
If there is any error please attached debug information in "\*Messages\*" buffer to your email.
** Packages
Please back up and remove original ~/.emacs.d.

Download zip or git clone from [[https://github.com/redguardtoo/emacs.d]]

Use this as emacs setup.

- Start Emacs, "M-x list-packages", ignore any error in this step
- restart Emacs, all packages should be downloaded and installed without any problem.

** Org-mode
Open ~/hello/hello.org by "C-x C-f".
** C
Open ~/hello/hello.c

insert single character "i" and press "M-j", the text should be expanded by yasnippet.
** Javascript
Open ~/hello/hello.js

insert single character "l" and press "M-j", the text should be expanded by yasnippet.

Please input some javascript with syntax error intentionally, the error will be highlighted immediately.
** HTML
Open ~/hello/hello.html

Install "tidy" (check README), then intentionally input some invalid html tag, you should see the tag is highlighted

Install "aspell" and its English dictionary, input some typo in html tag's "value" attribute. The typo will be highlighted automatically.
** Ruby
Open ~/hello/hello.rb
** Python
Open ~/hello/hello.py
** Perl
Open ~/hello/hello.pl
* Report
Email me,
- the environment information (Emacs version, OS details)
- any bug report
- any general issues not covered by this document
