;;; company-coq-abbrev.el --- List of tactics, auto-generated from RefMan

;; Copyright (C) 2015  Clément Pit--Claudel
;; Author: Clément Pit--Claudel <clement.pitclaudel@live.com>
;; URL: https://github.com/cpitclaudel/company-coq

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;;; Code:

(defconst company-coq-abbrevs
  (list
    '("Theorem @{ident} : @{type}." . ("14" . 9))
    '("Theorem @{ident} @{binders} : @{type}." . ("14" . 9))
    '("Lemma @{ident} : @{type}." . ("14" . 12))
    '("Lemma @{ident} @{binders} : @{type}." . ("14" . 12))
    '("Remark @{ident} : @{type}." . ("14" . 13))
    '("Remark @{ident} @{binders} : @{type}." . ("14" . 13))
    '("Fact @{ident} : @{type}." . ("14" . 14))
    '("Fact @{ident} @{binders} : @{type}." . ("14" . 14))
    '("Corollary @{ident} : @{type}." . ("14" . 15))
    '("Corollary @{ident} @{binders} : @{type}." . ("14" . 15))
    '("Proposition @{ident} : @{type}." . ("14" . 16))
    '("Proposition @{ident} @{binders} : @{type}." . ("14" . 16))
    '("Definition @{ident} : @{type}." . ("14" . 17))
    '("Definition @{ident} @{binders} : @{type}." . ("14" . 17))
    '("Let @{ident} : @{type}." . ("14" . 18))
    '("Let @{ident} @{binders} : @{type}." . ("14" . 18))
    '("Unset Printing Records." . ("16" . 21))
    '("Add Printing Record @{ident}." . ("16" . 22))
    '("Add Printing Constructor @{ident}." . ("16" . 23))
    '("Set Printing Projections." . ("16" . 24))
    '("Unset Printing Projections." . ("16" . 24))
    '("Test Printing Projections." . ("16" . 24))
    '("Set Printing Matching." . ("1c" . 25))
    '("Unset Printing Matching." . ("1c" . 26))
    '("Test Printing Matching." . ("1c" . 27))
    '("Set Printing Wildcard." . ("1c" . 28))
    '("Unset Printing Wildcard." . ("1c" . 29))
    '("Test Printing Wildcard." . ("1c" . 30))
    '("Set Printing Synth." . ("1c" . 31))
    '("Unset Printing Synth." . ("1c" . 32))
    '("Test Printing Synth." . ("1c" . 33))
    '("Add Printing Let @{ident}." . ("1c" . 34))
    '("Remove Printing Let @{ident}." . ("1c" . 35))
    '("Test Printing Let for @{ident}." . ("1c" . 36))
    '("Print Table Printing Let." . ("1c" . 37))
    '("Add Printing If @{ident}." . ("1c" . 38))
    '("Remove Printing If @{ident}." . ("1c" . 39))
    '("Test Printing If for @{ident}." . ("1c" . 40))
    '("Print Table Printing If." . ("1c" . 41))
    '("Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 50))
    '("Arguments @{qualid} : clear implicits." . ("1p" . 51))
    '("Global Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 52))
    '("Local Arguments @{qualid} @{possibly_bracketed_ident+}." . ("1p" . 53))
    '("Arguments @{qualid} : default implicits." . ("1q" . 54))
    '("Set Implicit Arguments." . ("1r" . 55))
    '("Unset Implicit Arguments." . ("1r" . 55))
    '("Test Implicit Arguments." . ("1r" . 55))
    '("Unset Strict Implicit." . ("1s" . 56))
    '("Set Strongly Strict Implicit." . ("1s" . 57))
    '("Unset Strongly Strict Implicit." . ("1s" . 57))
    '("Test Strongly Strict Implicit." . ("1s" . 57))
    '("Set Contextual Implicit." . ("1t" . 58))
    '("Unset Contextual Implicit." . ("1t" . 58))
    '("Test Contextual Implicit." . ("1t" . 58))
    '("Set Reversible Pattern Implicit." . ("1u" . 59))
    '("Unset Reversible Pattern Implicit." . ("1u" . 59))
    '("Test Reversible Pattern Implicit." . ("1u" . 59))
    '("Set Maximal Implicit Insertion." . ("1v" . 60))
    '("Unset Maximal Implicit Insertion." . ("1v" . 60))
    '("Test Maximal Implicit Insertion." . ("1v" . 60))
    '("Arguments @{qualid} @{name+} : rename." . ("1x" . 61))
    '("Print Implicit @{qualid}." . ("1y" . 62))
    '("Set Printing Implicit." . ("1z" . 63))
    '("Test Printing Implicit." . ("1z" . 63))
    '("Unset Printing Implicit." . ("1z" . 64))
    '("Unset Printing Implicit Defensive." . ("1z" . 65))
    '("Set Printing Implicit Defensive." . ("1z" . 66))
    '("Test Printing Implicit Defensive." . ("1z" . 66))
    '("Set Parsing Explicit." . ("21" . 67))
    '("Unset Parsing Explicit." . ("21" . 67))
    '("Test Parsing Explicit." . ("21" . 67))
    '("Canonical Structure @{qualid}." . ("22" . 69))
    '("Implicit Types @{ident+} : @{type}." . ("23" . 70))
    '("Generalizable All Variables." . ("24" . 71))
    '("Generalizable No Variables." . ("24" . 72))
    '("Generalizable Variable @{ident}." . ("24" . 73))
    '("Generalizable Variables @{ident+}." . ("24" . 74))
    '("Global Generalizable All Variables." . ("24" . 75))
    '("Coercion @{qualid} : @{class} >-> @{class}." . ("25" . 76))
    '("Set Printing All." . ("26" . 77))
    '("Test Printing All." . ("26" . 77))
    '("Unset Printing All." . ("26" . 78))
    '("Set Printing Universes." . ("27" . 79))
    '("Test Printing Universes." . ("27" . 79))
    '("Unset Printing Universes." . ("27" . 80))
    '("Print Universes." . ("27" . 81))
    '("Print Sorted Universes." . ("27" . 81))
    '("Print Universes \"@{string}\"." . ("27" . 82))
    '("Print Sorted Universes \"@{string}\"." . ("27" . 82))
    '("Set Printing Existential Instances." . ("29" . 83))
    '("Test Printing Existential Instances." . ("29" . 83))
    '("Unset Printing Existential Instances." . ("29" . 84))
    '("Module @{ident}." . ("2c" . 86))
    '("Module @{ident} @{module_bindings}." . ("2c" . 97))
    '("Module @{ident} : @{module_type}." . ("2c" . 98))
    '("Module @{ident} @{module_bindings} : @{module_type}." . ("2c" . 99))
    '("Module @{ident} <: @{module_type<:+}." . ("2c" . 100))
    '("Module @{ident} @{module_bindings} <: @{module_type<:+}." . ("2c" . 101))
    '("Include @{module}." . ("2c" . 102))
    '("Include @{module<++}." . ("2c" . 103))
    '("End @{ident}." . ("2c" . 106))
    '("Module @{ident} := @{module_expression}." . ("2c" . 110))
    '("Module @{ident} @{module_bindings} := @{module_expression}." . ("2c" . 111))
    '("Module @{ident} @{module_bindings} : @{module_type} := @{module_expression}." . ("2c" . 112))
    '("Module @{ident} @{module_bindings} <: @{module_type<:+}:= @{module_expression}." . ("2c" . 113))
    '("Module @{ident} @{module_bindings} := @{module_expression<++}." . ("2c" . 114))
    '("Module Type @{ident}." . ("2c" . 115))
    '("Module Type @{ident} @{module_bindings}." . ("2c" . 116))
    '("@{assumption_keyword} Inline @{assums}." . ("2c" . 119))
    '("Module Type @{ident} := @{module_type}." . ("2c" . 122))
    '("Module Type @{ident} @{module_bindings} := @{module_type}." . ("2c" . 123))
    '("Module Type @{ident} @{module_bindings} := @{module_type<++}." . ("2c" . 124))
    '("Declare Module @{ident} : @{module_type}." . ("2c" . 125))
    '("Declare Module @{ident} @{module_bindings} : @{module_type}." . ("2c" . 126))
    '("Import @{qualid}." . ("2c" . 127))
    '("Export @{qualid}." . ("2c" . 128))
    '("Print Module @{ident}." . ("2c" . 130))
    '("Print Module Type @{ident}." . ("2c" . 131))
    '("Locate Module @{qualid}." . ("2c" . 132))
    '("discrR" . ("30" . 122))
    '("split_Rabs" . ("30" . 123))
    '("split_Rmult" . ("30" . 124))
    '("Print @{qualid}." . ("3t" . 126))
    '("Print Term @{qualid}." . ("3t" . 128))
    '("About @{qualid}." . ("3t" . 129))
    '("Print All." . ("3u" . 130))
    '("Inspect @{num}." . ("3u" . 131))
    '("Print Section @{ident}." . ("3u" . 132))
    '("Set @{flag}." . ("3w" . 133))
    '("Local Set @{flag}." . ("3w" . 134))
    '("Global Set @{flag}." . ("3w" . 135))
    '("Unset @{flag}." . ("3x" . 136))
    '("Local Unset @{flag}." . ("3x" . 137))
    '("Global Unset @{flag}." . ("3x" . 138))
    '("Test @{flag}." . ("3y" . 139))
    '("Set @{option} @{value}." . ("3z" . 140))
    '("Unset @{option} @{value}." . ("3z" . 140))
    '("Test @{option} @{value}." . ("3z" . 140))
    '("Local Set @{option} @{value}." . ("3z" . 141))
    '("Global Set @{option} @{value}." . ("3z" . 142))
    '("Unset @{option}." . ("40" . 143))
    '("Local Unset @{option}." . ("40" . 144))
    '("Global Unset @{option}." . ("40" . 145))
    '("Test @{option}." . ("41" . 146))
    '("Print Options." . ("43" . 147))
    '("Print Tables." . ("43" . 148))
    '("Check @{term}." . ("45" . 149))
    '("@{selector}: Check @{term}." . ("45" . 150))
    '("Eval @{convtactic} in @{term}." . ("46" . 151))
    '("Compute @{term}." . ("47" . 152))
    '("Extraction @{term}." . ("48" . 153))
    '("Recursive Extraction @{qualid+}." . ("48" . 154))
    '("Print Assumptions @{qualid}." . ("49" . 155))
    '("Print Opaque Dependencies @{qualid}." . ("49" . 156))
    '("Print Transparent Dependencies @{qualid}." . ("49" . 157))
    '("Print All Dependencies @{qualid}." . ("49" . 158))
    '("Search @{qualid}." . ("4a" . 159))
    '("Search \"@{string}\"." . ("4a" . 161))
    '("Search \"@{string}\"%@{key}." . ("4a" . 162))
    '("Search @{term_pattern}." . ("4a" . 163))
    '("Search @{search_term+}." . ("4a" . 164))
    '("Search -@{search_term+}." . ("4a" . 164))
    '("Search @{search_term+} inside @{module+}." . ("4a" . 165))
    '("Search @{search_term+} outside @{module+}." . ("4a" . 166))
    '("@{selector}: Search @{search_term+}." . ("4a" . 167))
    '("@{selector}: Search -@{search_term+}." . ("4a" . 167))
    '("SearchAbout @{qualid}." . ("4a" . 168))
    '("SearchHead @{term}." . ("4b" . 169))
    '("SearchHead @{term} inside @{module+}." . ("4b" . 170))
    '("SearchHead @{term} outside @{module+}." . ("4b" . 171))
    '("@{selector}: SearchHead @{term}." . ("4b" . 173))
    '("SearchPattern @{term}." . ("4c" . 174))
    '("SearchPattern @{term} inside @{module+}." . ("4c" . 175))
    '("SearchPattern @{term} outside @{module+}." . ("4c" . 176))
    '("@{selector}: SearchPattern @{term}." . ("4c" . 177))
    '("SearchRewrite @{term}." . ("4d" . 178))
    '("SearchRewrite @{term} inside @{module+}." . ("4d" . 179))
    '("SearchRewrite @{term} outside @{module+}." . ("4d" . 180))
    '("@{selector}: SearchRewrite @{term}." . ("4d" . 181))
    '("Add Search Blacklist \"@{string}\"." . ("4d" . 182))
    '("Remove Search Blacklist \"@{string}\"." . ("4d" . 183))
    '("Locate @{qualid}." . ("4e" . 184))
    '("Locate Term @{qualid}." . ("4e" . 185))
    '("Locate Ltac @{qualid}." . ("4e" . 187))
    '("Load @{ident}." . ("4g" . 188))
    '("Load \"@{string}\"." . ("4g" . 189))
    '("Load Verbose @{ident}." . ("4g" . 190))
    '("Load Verbose \"@{string}\"." . ("4g" . 191))
    '("Require @{qualid}." . ("4i" . 193))
    '("Require Import @{qualid}." . ("4i" . 194))
    '("Require Export @{qualid}." . ("4i" . 195))
    '("Require @{qualid+}." . ("4i" . 196))
    '("Require @{Import|Export} @{qualid+}." . ("4i" . 196))
    '("From @{dirpath} Require @{qualid}." . ("4i" . 197))
    '("Print Libraries." . ("4j" . 204))
    '("Declare ML Module \"@{string}\" .. \"@{string}\"." . ("4k" . 205))
    '("Local Declare ML Module \"@{string}\" .. \"@{string}\"." . ("4k" . 206))
    '("Print ML Modules." . ("4l" . 209))
    '("Pwd." . ("4n" . 210))
    '("Cd \"@{string}\"." . ("4o" . 211))
    '("Cd." . ("4o" . 212))
    '("Add LoadPath \"@{string}\" as @{dirpath}." . ("4p" . 213))
    '("Add LoadPath \"@{string}\"." . ("4p" . 214))
    '("Add Rec LoadPath \"@{string}\" as @{dirpath}." . ("4q" . 215))
    '("Add Rec LoadPath \"@{string}\"." . ("4q" . 216))
    '("Remove LoadPath \"@{string}\"." . ("4r" . 217))
    '("Print LoadPath." . ("4s" . 218))
    '("Print LoadPath @{dirpath}." . ("4s" . 219))
    '("Add ML Path \"@{string}\"." . ("4t" . 220))
    '("Add Rec ML Path \"@{string}\"." . ("4u" . 221))
    '("Print ML Path \"@{string}\"." . ("4v" . 222))
    '("Locate File \"@{string}\"." . ("4w" . 223))
    '("Locate Library @{dirpath}." . ("4x" . 224))
    '("Reset @{ident}." . ("4z" . 225))
    '("Back." . ("50" . 227))
    '("Back @{n}." . ("50" . 228))
    '("BackTo @{num}." . ("51" . 230))
    '("Backtrack @{num} @{num} @{num}." . ("51" . 231))
    '("Quit." . ("53" . 233))
    '("Drop." . ("54" . 234))
    '("Time @{command}." . ("55" . 235))
    '("Timeout @{int} @{command}." . ("56" . 236))
    '("Set Default Timeout @{int}." . ("57" . 237))
    '("Unset Default Timeout @{int}." . ("57" . 237))
    '("Test Default Timeout @{int}." . ("57" . 237))
    '("Unset Default Timeout." . ("58" . 238))
    '("Test Default Timeout." . ("59" . 239))
    '("Set Silent." . ("5b" . 240))
    '("Test Silent." . ("5b" . 240))
    '("Unset Silent." . ("5c" . 241))
    '("Set Printing Width @{integer}." . ("5d" . 242))
    '("Unset Printing Width @{integer}." . ("5d" . 242))
    '("Test Printing Width @{integer}." . ("5d" . 242))
    '("Unset Printing Width." . ("5e" . 243))
    '("Test Printing Width." . ("5f" . 244))
    '("Set Printing Depth @{integer}." . ("5g" . 245))
    '("Unset Printing Depth @{integer}." . ("5g" . 245))
    '("Test Printing Depth @{integer}." . ("5g" . 245))
    '("Unset Printing Depth." . ("5h" . 246))
    '("Test Printing Depth." . ("5i" . 247))
    '("Opaque @{qualid+}." . ("5k" . 248))
    '("Global Opaque @{qualid+}." . ("5k" . 249))
    '("Transparent @{qualid+}." . ("5l" . 251))
    '("Strategy @{level} [@{qualid+}]." . ("5m" . 253))
    '("Print Strategy @{qualid}." . ("5n" . 254))
    '("Print Strategies." . ("5n" . 255))
    '("Declare Reduction @{ident} := @{convtactic}." . ("5o" . 256))
    '("Set Virtual Machine." . ("5p" . 257))
    '("Unset Virtual Machine." . ("5q" . 258))
    '("Test Virtual Machine." . ("5r" . 259))
    '("Local." . ("5t" . 260))
    '("Global." . ("5t" . 261))
    '("Goal @{form}." . ("5w" . 263))
    '("Qed." . ("5x" . 264))
    '("Defined." . ("5x" . 266))
    '("Save." . ("5x" . 267))
    '("Save @{ident}." . ("5x" . 268))
    '("Save Theorem @{ident}." . ("5x" . 269))
    '("Save Lemma @{ident}." . ("5x" . 270))
    '("Save Remark @{ident}." . ("5x" . 271))
    '("Save Fact @{ident}." . ("5x" . 272))
    '("Save Corollary @{ident}." . ("5x" . 273))
    '("Save Proposition @{ident}." . ("5x" . 274))
    '("Admitted." . ("5y" . 275))
    '("Proof @{term}." . ("5z" . 276))
    '("Proof." . ("5z" . 277))
    '("Proof using @{ident+}." . ("60" . 278))
    '("Proof using @{ident+} with @{tactic}." . ("60" . 279))
    '("Proof using All." . ("60" . 280))
    '("Proof using Type." . ("60" . 281))
    '("Proof using." . ("60" . 282))
    '("Proof using -(@{ident+})." . ("60" . 283))
    '("Proof using @{collection} + @{collection}." . ("60" . 284))
    '("Proof using @{collection} - @{collection}." . ("60" . 285))
    '("Proof using @{collection} - (@{ident+})." . ("60" . 286))
    '("Set Default Proof Using \"@{expression}\"." . ("60" . 287))
    '("Unset Default Proof Using \"@{expression}\"." . ("60" . 287))
    '("Test Default Proof Using \"@{expression}\"." . ("60" . 287))
    '("Set Suggest Proof Using." . ("60" . 288))
    '("Unset Suggest Proof Using." . ("60" . 288))
    '("Test Suggest Proof Using." . ("60" . 288))
    '("Collection @{ident}:= @{ident+}." . ("60" . 289))
    '("Abort." . ("61" . 290))
    '("Abort @{ident}." . ("61" . 292))
    '("Abort All." . ("61" . 293))
    '("Existential @{num} := @{term}." . ("62" . 294))
    '("Grab Existential Variables." . ("63" . 295))
    '("Undo." . ("65" . 296))
    '("Undo @{num}." . ("65" . 297))
    '("Restart." . ("66" . 298))
    '("Focus." . ("67" . 300))
    '("Focus @{num}." . ("67" . 301))
    '("Unfocus." . ("68" . 302))
    '("Unfocused." . ("69" . 303))
    '("Show." . ("6d" . 309))
    '("Show @{num}." . ("6d" . 310))
    '("Show Script." . ("6d" . 313))
    '("Show Proof." . ("6d" . 314))
    '("Show Conjectures." . ("6d" . 315))
    '("Show Intro." . ("6d" . 316))
    '("Show Intros." . ("6d" . 317))
    '("Show Existentials." . ("6d" . 318))
    '("Guarded." . ("6e" . 319))
    '("Set Hyps Limit @{num}." . ("6g" . 320))
    '("Unset Hyps Limit @{num}." . ("6g" . 320))
    '("Test Hyps Limit @{num}." . ("6g" . 320))
    '("Unset Hyps Limit." . ("6h" . 321))
    '("Set Automatic Introduction." . ("6i" . 322))
    '("Test Automatic Introduction." . ("6i" . 322))
    '("Unset Automatic Introduction." . ("6i" . 323))
    '("Optimize Proof." . ("6k" . 324))
    '("Optimize Heap." . ("6l" . 325))
    '("Set Default Goal Selector \"@{selector}\"." . ("6o" . 326))
    '("Unset Default Goal Selector \"@{selector}\"." . ("6o" . 326))
    '("Test Default Goal Selector \"@{selector}\"." . ("6o" . 326))
    '("Test Default Goal Selector." . ("6p" . 327))
    '("exact @{term}" . ("6t" . 330))
    '("eexact @{term}" . ("6t" . 332))
    '("assumption" . ("6u" . 333))
    '("eassumption" . ("6u" . 335))
    '("refine @{term}" . ("6v" . 336))
    '("apply @{term}" . ("6w" . 339))
    '("apply @{term} with @{term+}" . ("6w" . 342))
    '("apply @{term} with (@{ref&} := @{term&})" . ("6w" . 344))
    '("apply @{term,+}" . ("6w" . 345))
    '("eapply @{term}" . ("6w" . 346))
    '("simple apply @{term}" . ("6w" . 347))
    '("lapply @{term}" . ("6w" . 348))
    '("apply @{term} in @{ident}" . ("6x" . 349))
    '("apply @{term,+} in @{ident}" . ("6x" . 352))
    '("apply @{term,&} with @{bindings_list,&} in @{ident}" . ("6x" . 353))
    '("eapply @{term,&} with @{bindings_list,&} in @{ident}" . ("6x" . 354))
    '("apply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6x" . 355))
    '("eapply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6x" . 356))
    '("simple apply @{term} in @{ident}" . ("6x" . 357))
    '("apply @{term,&} in @{ident}" . ("6x" . 358))
    '("apply @{term,&} in @{ident} as @{intro_pattern}" . ("6x" . 358))
    '("simple apply @{term,&} in @{ident}" . ("6x" . 358))
    '("simple apply @{term,&} in @{ident} as @{intro_pattern}" . ("6x" . 358))
    '("simple apply @{term,&} with @{bindings_list,&} in @{ident}" . ("6x" . 358))
    '("simple apply @{term,&} with @{bindings_list,&} in @{ident} as @{intro_pattern}" . ("6x" . 358))
    '("constructor @{num}" . ("6y" . 359))
    '("constructor" . ("6y" . 362))
    '("constructor @{num} with" . ("6y" . 363))
    '("split" . ("6y" . 364))
    '("exists @{bindings_list}" . ("6y" . 366))
    '("exists @{bindings_list,+}" . ("6y" . 368))
    '("left" . ("6y" . 369))
    '("right" . ("6y" . 370))
    '("left with @{bindings_list}" . ("6y" . 372))
    '("right with @{bindings_list}" . ("6y" . 373))
    '("split with @{bindings_list}" . ("6y" . 374))
    '("econstructor" . ("6y" . 375))
    '("eexists" . ("6y" . 376))
    '("esplit" . ("6y" . 377))
    '("eleft" . ("6y" . 378))
    '("eright" . ("6y" . 379))
    '("intro" . ("70" . 380))
    '("intros" . ("70" . 383))
    '("intro @{ident}" . ("70" . 384))
    '("intros @{ident+}" . ("70" . 386))
    '("intros until @{ident}" . ("70" . 387))
    '("intros until @{num}" . ("70" . 389))
    '("intro after @{ident}" . ("70" . 391))
    '("intro before @{ident}" . ("70" . 392))
    '("intro at top" . ("70" . 393))
    '("intro at bottom" . ("70" . 394))
    '("intro @{ident} after @{ident}" . ("70" . 396))
    '("intro @{ident} before @{ident}" . ("70" . 397))
    '("intro @{ident} at top" . ("70" . 398))
    '("intro @{ident} at bottom" . ("70" . 399))
    '("intros @{intro_pattern+}" . ("72" . 400))
    '("clear @{ident}" . ("73" . 401))
    '("clear @{ident+}" . ("73" . 405))
    '("clearbody @{ident}" . ("73" . 406))
    '("clear - @{ident+}" . ("73" . 408))
    '("clear" . ("73" . 409))
    '("clear dependent @{ident}" . ("73" . 410))
    '("revert @{ident+}" . ("74" . 411))
    '("revert dependent @{ident}" . ("74" . 414))
    '("move @{ident} after @{ident}" . ("75" . 415))
    '("move @{ident} before @{ident}" . ("75" . 416))
    '("move @{ident} at top" . ("75" . 417))
    '("move @{ident} at bottom" . ("75" . 418))
    '("rename @{ident} into @{ident}" . ("76" . 422))
    '("rename @{ident,&} into @{ident,&}" . ("76" . 423))
    '("set (@{ident} := @{term})" . ("77" . 426))
    '("set (@{ident} := @{term}) in @{goal_occurrences}" . ("77" . 428))
    '("set (@{ident} @{binder+} := @{term})" . ("77" . 429))
    '("set @{term}" . ("77" . 430))
    '("set (@{ident} @{binder+} := @{term}) in @{goal_occurrences}" . ("77" . 431))
    '("set @{term} in @{goal_occurrences}" . ("77" . 432))
    '("remember @{term} as @{ident}" . ("77" . 433))
    '("remember @{term} as @{ident} eqn:@{ident}" . ("77" . 434))
    '("remember @{term} as @{ident} in @{goal_occurrences}" . ("77" . 435))
    '("pose (@{ident} := @{term})" . ("77" . 436))
    '("pose (@{ident} @{binder+} := @{term})" . ("77" . 437))
    '("pose @{term}" . ("77" . 438))
    '("decompose [@{qualid+}] @{term}" . ("78" . 439))
    '("decompose sum @{term}" . ("78" . 440))
    '("decompose record @{term}" . ("78" . 441))
    '("assert (@{ident} : @{form})" . ("7a" . 442))
    '("assert @{form}" . ("7a" . 444))
    '("assert @{form} by @{tactic}" . ("7a" . 445))
    '("assert @{form} as @{intro_pattern}" . ("7a" . 447))
    '("assert @{form} as @{intro_pattern} by @{tactic}" . ("7a" . 448))
    '("assert (@{ident} := @{term})" . ("7a" . 449))
    '("pose proof @{term} as @{intro_pattern}" . ("7a" . 451))
    '("enough (@{ident} : @{form})" . ("7a" . 452))
    '("enough @{form}" . ("7a" . 453))
    '("enough @{form} as @{intro_pattern}" . ("7a" . 454))
    '("enough (@{ident} : @{form}) by @{tactic}" . ("7a" . 455))
    '("enough @{form} by @{tactic}" . ("7a" . 456))
    '("enough @{form} as @{intro_pattern} by @{tactic}" . ("7a" . 457))
    '("cut @{form}" . ("7a" . 458))
    '("specialize (@{ident} @{term+})" . ("7a" . 459))
    '("specialize @{ident} with @{bindings_list}" . ("7a" . 460))
    '("generalize @{term}" . ("7c" . 463))
    '("generalize @{term,+}" . ("7c" . 464))
    '("generalize @{term} at @{num+}" . ("7c" . 465))
    '("generalize @{term} as @{ident}" . ("7c" . 466))
    '("generalize @{term,&} at @{num+,&} as @{ident,&}" . ("7c" . 467))
    '("generalize dependent @{term}" . ("7c" . 468))
    '("evar (@{ident} : @{term})" . ("7d" . 469))
    '("instantiate (@{num} := @{term})" . ("7e" . 470))
    '("instantiate (@{num} := @{term}) in @{ident}" . ("7e" . 471))
    '("instantiate (@{num} := @{term}) in (Value of @{ident})" . ("7e" . 472))
    '("instantiate (@{num} := @{term}) in (Type of @{ident})" . ("7e" . 473))
    '("instantiate" . ("7e" . 474))
    '("absurd @{term}" . ("7f" . 475))
    '("contradiction" . ("7g" . 476))
    '("contradiction @{ident}" . ("7g" . 478))
    '("contradict @{ident}" . ("7h" . 479))
    '("exfalso" . ("7i" . 480))
    '("destruct @{term}" . ("7k" . 481))
    '("destruct @{term,+}" . ("7k" . 482))
    '("destruct @{term} as @{disj_conj_intro_pattern}" . ("7k" . 483))
    '("destruct @{term} eqn:@{naming_intro_pattern}" . ("7k" . 484))
    '("destruct @{term} with @{bindings_list}" . ("7k" . 485))
    '("edestruct @{term}" . ("7k" . 486))
    '("destruct @{term} using @{term}" . ("7k" . 487))
    '("destruct @{term} using @{term} with @{bindings_list}" . ("7k" . 488))
    '("destruct @{term} in @{goal_occurrences}" . ("7k" . 489))
    '("destruct @{term} with @{bindings_list} as @{disj_conj_intro_pattern} eqn:@{naming_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7k" . 490))
    '("edestruct @{term} with @{bindings_list} as @{disj_conj_intro_pattern} eqn:@{naming_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7k" . 491))
    '("destruct !@{ident}" . ("7k" . 492))
    '("case @{term}" . ("7k" . 493))
    '("case @{term} with @{bindings_list}" . ("7k" . 494))
    '("ecase @{term}" . ("7k" . 495))
    '("ecase @{term} with @{bindings_list}" . ("7k" . 496))
    '("simple destruct @{ident}" . ("7k" . 497))
    '("simple destruct @{num}" . ("7k" . 498))
    '("case_eq @{term}" . ("7k" . 499))
    '("induction @{term}" . ("7l" . 500))
    '("induction @{term} as @{disj_conj_intro_pattern}" . ("7l" . 503))
    '("induction @{term} with @{bindings_list}" . ("7l" . 504))
    '("einduction @{term}" . ("7l" . 505))
    '("induction @{term} using @{term}" . ("7l" . 506))
    '("induction @{term} using @{term} with @{bindings_list}" . ("7l" . 507))
    '("induction @{term,+} using @{qualid}" . ("7l" . 508))
    '("induction @{term} in @{goal_occurrences}" . ("7l" . 509))
    '("induction @{term} with @{bindings_list} as @{disj_conj_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7l" . 510))
    '("einduction @{term} with @{bindings_list} as @{disj_conj_intro_pattern} using @{term} with @{bindings_list} in @{goal_occurrences}" . ("7l" . 511))
    '("induction !@{ident}" . ("7l" . 512))
    '("elim @{term}" . ("7l" . 513))
    '("elim @{term} with @{bindings_list}" . ("7l" . 514))
    '("eelim @{term}" . ("7l" . 515))
    '("elim @{term} using @{term}" . ("7l" . 516))
    '("elim @{term} using @{term} with @{bindings_list}" . ("7l" . 517))
    '("elim @{term} with @{bindings_list} using @{term} with @{bindings_list}" . ("7l" . 518))
    '("eelim @{term} with @{bindings_list} using @{term} with @{bindings_list}" . ("7l" . 519))
    '("elimtype @{form}" . ("7l" . 520))
    '("simple induction @{ident}" . ("7l" . 521))
    '("simple induction @{num}" . ("7l" . 522))
    '("double induction @{ident} @{ident}" . ("7m" . 523))
    '("double induction @{num} @{num}" . ("7m" . 524))
    '("dependent induction @{ident}" . ("7n" . 525))
    '("dependent induction @{ident} generalizing @{ident+}" . ("7n" . 526))
    '("dependent destruction @{ident}" . ("7n" . 527))
    '("functional induction (@{qualid} @{term+})" . ("7o" . 528))
    '("functional induction (@{qualid} @{term+}) as @{disj_conj_intro_pattern} using @{term} with @{bindings_list}" . ("7o" . 531))
    '("discriminate @{term}" . ("7p" . 532))
    '("discriminate @{num}" . ("7p" . 535))
    '("discriminate @{term} with @{bindings_list}" . ("7p" . 536))
    '("ediscriminate @{num}" . ("7p" . 537))
    '("ediscriminate @{term}" . ("7p" . 538))
    '("ediscriminate @{term} with @{bindings_list}" . ("7p" . 538))
    '("discriminate" . ("7p" . 539))
    '("injection @{term}" . ("7r" . 541))
    '("injection @{num}" . ("7r" . 545))
    '("injection @{term} with @{bindings_list}" . ("7r" . 546))
    '("einjection @{num}" . ("7r" . 547))
    '("einjection @{term}" . ("7r" . 548))
    '("einjection @{term} with @{bindings_list}" . ("7r" . 548))
    '("injection" . ("7r" . 549))
    '("injection @{term} as @{intro_pattern+}" . ("7r" . 551))
    '("injection @{term} with @{bindings_list} as @{intro_pattern+}" . ("7r" . 551))
    '("injection @{num} as @{intro_pattern+}" . ("7r" . 552))
    '("injection as @{intro_pattern+}" . ("7r" . 553))
    '("einjection @{term} as @{intro_pattern+}" . ("7r" . 554))
    '("einjection @{term} with @{bindings_list} as @{intro_pattern+}" . ("7r" . 554))
    '("einjection @{num} as @{intro_pattern+}" . ("7r" . 555))
    '("einjection as @{intro_pattern+}" . ("7r" . 556))
    '("inversion @{ident}" . ("7s" . 557))
    '("inversion @{num}" . ("7s" . 558))
    '("inversion_clear @{ident}" . ("7s" . 559))
    '("inversion @{ident} as @{intro_pattern}" . ("7s" . 560))
    '("inversion @{num} as @{intro_pattern}" . ("7s" . 561))
    '("inversion_clear @{ident} as @{intro_pattern}" . ("7s" . 562))
    '("inversion @{ident} in @{ident+}" . ("7s" . 563))
    '("inversion @{ident} as @{intro_pattern} in @{ident+}" . ("7s" . 564))
    '("inversion_clear @{ident} in @{ident+}" . ("7s" . 565))
    '("inversion_clear @{ident} as @{intro_pattern} in @{ident+}" . ("7s" . 566))
    '("dependent inversion @{ident}" . ("7s" . 567))
    '("dependent inversion @{ident} as @{intro_pattern}" . ("7s" . 568))
    '("dependent inversion_clear @{ident}" . ("7s" . 569))
    '("dependent inversion_clear @{ident} as @{intro_pattern}" . ("7s" . 570))
    '("dependent inversion @{ident} with @{term}" . ("7s" . 571))
    '("dependent inversion @{ident} as @{intro_pattern} with @{term}" . ("7s" . 572))
    '("dependent inversion_clear @{ident} with @{term}" . ("7s" . 574))
    '("dependent inversion_clear @{ident} as @{intro_pattern} with @{term}" . ("7s" . 575))
    '("simple inversion @{ident}" . ("7s" . 576))
    '("simple inversion @{ident} as @{intro_pattern}" . ("7s" . 577))
    '("inversion @{ident} using @{ident'}" . ("7s" . 578))
    '("inversion @{ident} using @{ident'} in @{ident+}" . ("7s" . 579))
    '("fix @{ident} @{num}" . ("7t" . 580))
    '("fix @{ident} @{num} with (@{ident&} @{binder+&} : @{type&})" . ("7t" . 581))
    '("fix @{ident} @{num} with (@{ident&} @{binder+&} {struct @{ident'&}} : @{type&})" . ("7t" . 581))
    '("cofix @{ident}" . ("7u" . 582))
    '("cofix @{ident} with (@{ident&} @{binder+&} : @{type&})" . ("7u" . 583))
    '("rewrite @{term}" . ("7w" . 584))
    '("rewrite -> @{term}" . ("7w" . 587))
    '("rewrite <- @{term}" . ("7w" . 588))
    '("rewrite @{term} in @{clause}" . ("7w" . 589))
    '("rewrite @{term} at @{occurrences}" . ("7w" . 590))
    '("rewrite @{term} by @{tactic}" . ("7w" . 591))
    '("rewrite @{term,+}" . ("7w" . 592))
    '("erewrite @{term}" . ("7w" . 593))
    '("replace @{term} with @{term}" . ("7x" . 594))
    '("replace @{term} with @{term} by @{tactic}" . ("7x" . 596))
    '("replace @{term}" . ("7x" . 597))
    '("replace -> @{term}" . ("7x" . 598))
    '("replace <- @{term}" . ("7x" . 599))
    '("replace @{term} with @{term} in @{clause}" . ("7x" . 600))
    '("replace @{term} with @{term} in @{clause} by @{tactic}" . ("7x" . 601))
    '("replace @{term} in @{clause}" . ("7x" . 602))
    '("replace -> @{term} in @{clause}" . ("7x" . 603))
    '("replace <- @{term} in @{clause}" . ("7x" . 604))
    '("cutrewrite <- (@{term} = @{term})" . ("7x" . 605))
    '("cutrewrite -> (@{term} = @{term})" . ("7x" . 606))
    '("subst @{ident}" . ("7y" . 607))
    '("subst @{ident+}" . ("7y" . 608))
    '("stepl @{term}" . ("7z" . 609))
    '("stepl @{term} by @{tactic}" . ("7z" . 610))
    '("stepr @{term}" . ("7z" . 611))
    '("stepr @{term} by @{tactic}" . ("7z" . 612))
    '("Declare Right Step @{term}." . ("7z" . 613))
    '("change @{term}" . ("80" . 614))
    '("change @{term} with @{term}" . ("80" . 616))
    '("change @{term} at @{num+} with @{term}" . ("80" . 617))
    '("change @{term} in @{ident}" . ("80" . 618))
    '("change @{term} with @{term} in @{ident}" . ("80" . 619))
    '("change @{term} at @{num+} with @{term} in @{ident}" . ("80" . 620))
    '("cbv @{flag+}" . ("82" . 621))
    '("lazy @{flag+}" . ("82" . 622))
    '("compute" . ("82" . 623))
    '("cbv" . ("82" . 625))
    '("lazy" . ("82" . 626))
    '("compute [@{qualid+}]" . ("82" . 627))
    '("cbv [@{qualid+}]" . ("82" . 628))
    '("compute -[@{qualid+}]" . ("82" . 629))
    '("cbv -[@{qualid+}]" . ("82" . 630))
    '("lazy [@{qualid+}]" . ("82" . 631))
    '("lazy -[@{qualid+}]" . ("82" . 632))
    '("vm_compute" . ("82" . 633))
    '("native_compute" . ("82" . 634))
    '("red" . ("83" . 635))
    '("hnf" . ("84" . 637))
    '("cbn" . ("85" . 638))
    '("simpl" . ("85" . 639))
    '("cbn [@{qualid+}]" . ("85" . 640))
    '("cbn -[@{qualid+}]" . ("85" . 641))
    '("simpl @{pattern}" . ("85" . 642))
    '("simpl @{pattern} at @{num+}" . ("85" . 643))
    '("simpl @{qualid}" . ("85" . 644))
    '("simpl @{string}" . ("85" . 645))
    '("simpl @{qualid} at @{num+}" . ("85" . 646))
    '("simpl @{string} at @{num+}" . ("85" . 647))
    '("unfold @{qualid}" . ("86" . 648))
    '("unfold @{qualid,+}" . ("86" . 650))
    '("unfold @{qualid,&} at @{num,+,&}" . ("86" . 651))
    '("unfold @{string}" . ("86" . 652))
    '("unfold @{string}%@{key}" . ("86" . 653))
    '("unfold @{qualid_or_string,&} at @{num,+,&}" . ("86" . 654))
    '("fold @{term}" . ("87" . 655))
    '("fold" . ("87" . 656))
    '("pattern @{term}" . ("88" . 657))
    '("pattern @{term} at @{num+}" . ("88" . 658))
    '("pattern @{term} at - @{num+}" . ("88" . 659))
    '("pattern @{term,+}" . ("88" . 660))
    '("pattern @{term,&} at @{num+,&}" . ("88" . 661))
    '("pattern" . ("88" . 662))
    '("auto" . ("8b" . 664))
    '("auto @{num}" . ("8b" . 665))
    '("auto with @{ident+}" . ("8b" . 666))
    '("auto with *" . ("8b" . 667))
    '("auto using @{lemma,+}" . ("8b" . 668))
    '("auto using @{lemma,+} with @{ident+}" . ("8b" . 669))
    '("trivial" . ("8b" . 670))
    '("trivial with @{ident+}" . ("8b" . 671))
    '("trivial with *" . ("8b" . 672))
    '("eauto" . ("8c" . 673))
    '("autounfold with @{ident+}" . ("8d" . 674))
    '("autounfold with @{ident+} in @{clause}" . ("8d" . 675))
    '("autounfold with *" . ("8d" . 676))
    '("autorewrite with @{ident+}" . ("8e" . 677))
    '("autorewrite with @{ident+} using @{tactic}" . ("8e" . 678))
    '("autorewrite with @{ident+} in @{qualid}" . ("8e" . 679))
    '("autorewrite with @{ident+} in @{qualid} using @{tactic}" . ("8e" . 680))
    '("autorewrite with @{ident+} in @{clause}" . ("8e" . 681))
    '("Create HintDb @{ident}." . ("8h" . 682))
    '("Create HintDb @{ident} discriminated." . ("8h" . 682))
    '("Hint @{hint_definition} : @{ident+}." . ("8h" . 683))
    '("Hint @{hint_definition}." . ("8h" . 684))
    '("Local Hint @{hint_definition} : @{ident+}." . ("8h" . 685))
    '("Local Hint @{hint_definition}." . ("8h" . 686))
    '("Hint Resolve @{term}." . ("8h" . 687))
    '("Hint Resolve @{term} : @{ident+}." . ("8h" . 687))
    '("Local Hint Resolve @{term}." . ("8h" . 687))
    '("Local Hint Resolve @{term} : @{ident+}." . ("8h" . 687))
    '("Hint Resolve @{term+}." . ("8h" . 690))
    '("Hint Resolve @{term+} : @{ident+}." . ("8h" . 690))
    '("Local Hint Resolve @{term+}." . ("8h" . 690))
    '("Local Hint Resolve @{term+} : @{ident+}." . ("8h" . 690))
    '("Hint Immediate @{term}." . ("8h" . 691))
    '("Hint Immediate @{term} : @{ident+}." . ("8h" . 691))
    '("Local Hint Immediate @{term}." . ("8h" . 691))
    '("Local Hint Immediate @{term} : @{ident+}." . ("8h" . 691))
    '("Hint Immediate @{term+}." . ("8h" . 694))
    '("Hint Immediate @{term+} : @{ident+}." . ("8h" . 694))
    '("Local Hint Immediate @{term+}." . ("8h" . 694))
    '("Local Hint Immediate @{term+} : @{ident+}." . ("8h" . 694))
    '("Hint Constructors @{ident}." . ("8h" . 695))
    '("Hint Constructors @{ident} : @{ident+}." . ("8h" . 695))
    '("Local Hint Constructors @{ident}." . ("8h" . 695))
    '("Local Hint Constructors @{ident} : @{ident+}." . ("8h" . 695))
    '("Hint Constructors @{ident+}." . ("8h" . 698))
    '("Hint Constructors @{ident+} : @{ident+}." . ("8h" . 698))
    '("Local Hint Constructors @{ident+}." . ("8h" . 698))
    '("Local Hint Constructors @{ident+} : @{ident+}." . ("8h" . 698))
    '("Hint Unfold @{qualid}." . ("8h" . 699))
    '("Hint Unfold @{qualid} : @{ident+}." . ("8h" . 699))
    '("Local Hint Unfold @{qualid}." . ("8h" . 699))
    '("Local Hint Unfold @{qualid} : @{ident+}." . ("8h" . 699))
    '("Hint Unfold @{ident+}." . ("8h" . 700))
    '("Hint Unfold @{ident+} : @{ident+}." . ("8h" . 700))
    '("Local Hint Unfold @{ident+}." . ("8h" . 700))
    '("Local Hint Unfold @{ident+} : @{ident+}." . ("8h" . 700))
    '("Hint @{Transparent|Opaque} @{qualid}." . ("8h" . 701))
    '("Hint @{Transparent|Opaque} @{qualid} : @{ident+}." . ("8h" . 701))
    '("Local Hint @{Transparent|Opaque} @{qualid}." . ("8h" . 701))
    '("Local Hint @{Transparent|Opaque} @{qualid} : @{ident+}." . ("8h" . 701))
    '("Hint @{Transparent|Opaque} @{ident+}." . ("8h" . 702))
    '("Hint @{Transparent|Opaque} @{ident+} : @{ident+}." . ("8h" . 702))
    '("Local Hint @{Transparent|Opaque} @{ident+}." . ("8h" . 702))
    '("Local Hint @{Transparent|Opaque} @{ident+} : @{ident+}." . ("8h" . 702))
    '("Hint Extern @{num} => @{tactic}." . ("8h" . 703))
    '("Hint Extern @{num} => @{tactic} : @{ident+}." . ("8h" . 703))
    '("Hint Extern @{num} @{pattern} => @{tactic}." . ("8h" . 703))
    '("Hint Extern @{num} @{pattern} => @{tactic} : @{ident+}." . ("8h" . 703))
    '("Local Hint Extern @{num} => @{tactic}." . ("8h" . 703))
    '("Local Hint Extern @{num} => @{tactic} : @{ident+}." . ("8h" . 703))
    '("Local Hint Extern @{num} @{pattern} => @{tactic}." . ("8h" . 703))
    '("Local Hint Extern @{num} @{pattern} => @{tactic} : @{ident+}." . ("8h" . 703))
    '("Hint Local @{hint_definition} : @{ident+}." . ("8h" . 705))
    '("Hint Local @{hint_definition}." . ("8h" . 706))
    '("Remove Hints @{term+} : @{ident+}." . ("8j" . 707))
    '("Print Hint." . ("8k" . 708))
    '("Print Hint @{ident}." . ("8k" . 709))
    '("Print Hint *." . ("8k" . 710))
    '("Print HintDb @{ident}." . ("8k" . 711))
    '("Hint Rewrite @{term+} : @{ident+}." . ("8l" . 712))
    '("Hint Rewrite -> @{term+} : @{ident+}." . ("8l" . 713))
    '("Hint Rewrite <- @{term+} : @{ident+}." . ("8l" . 714))
    '("Hint Rewrite @{term+} using @{tactic} : @{ident+}." . ("8l" . 715))
    '("Print Rewrite HintDb @{ident}." . ("8l" . 716))
    '("Proof with @{tactic}." . ("8n" . 719))
    '("Proof with @{tactic} using @{ident+}." . ("8n" . 720))
    '("Declare Implicit Tactic @{tactic}." . ("8n" . 722))
    '("tauto" . ("8p" . 721))
    '("intuition @{tactic}" . ("8q" . 722))
    '("intuition" . ("8q" . 723))
    '("rtauto" . ("8r" . 724))
    '("firstorder" . ("8s" . 725))
    '("firstorder @{tactic}" . ("8s" . 726))
    '("firstorder with @{ident+}" . ("8s" . 727))
    '("firstorder using @{qualid,+}" . ("8s" . 728))
    '("firstorder using @{qualid,+} with @{ident+}" . ("8s" . 729))
    '("congruence" . ("8t" . 730))
    '("congruence @{n}" . ("8t" . 731))
    '("congruence with @{term+}" . ("8t" . 732))
    '("constr_eq @{term} @{term}" . ("8v" . 735))
    '("unify @{term} @{term}" . ("8w" . 737))
    '("unify @{term} @{term} with @{ident}" . ("8w" . 739))
    '("is_evar @{term}" . ("8x" . 740))
    '("has_evar @{term}" . ("8y" . 742))
    '("is_var @{term}" . ("8z" . 744))
    '("f_equal" . ("91" . 746))
    '("reflexivity" . ("92" . 747))
    '("symmetry" . ("93" . 750))
    '("symmetry in @{ident}" . ("93" . 751))
    '("transitivity @{term}" . ("94" . 752))
    '("decide equality" . ("96" . 753))
    '("compare @{term} @{term}" . ("97" . 754))
    '("simplify_eq @{term}" . ("98" . 755))
    '("simplify_eq @{num}" . ("98" . 756))
    '("simplify_eq" . ("98" . 757))
    '("esimplify_eq @{num}" . ("98" . 758))
    '("esimplify_eq @{term}" . ("98" . 759))
    '("esimplify_eq @{term} with @{bindings_list}" . ("98" . 759))
    '("dependent rewrite -> @{ident}" . ("99" . 761))
    '("dependent rewrite <- @{ident}" . ("99" . 762))
    '("functional inversion @{ident}" . ("9b" . 763))
    '("functional inversion @{num}" . ("9b" . 766))
    '("functional inversion @{ident} @{qualid}" . ("9b" . 767))
    '("quote @{ident}" . ("9c" . 768))
    '("quote @{ident} [@{ident+}]" . ("9c" . 770))
    '("classical_left" . ("9e" . 771))
    '("classical_right" . ("9e" . 772))
    '("btauto" . ("9g" . 773))
    '("omega" . ("9h" . 774))
    '("ring" . ("9i" . 775))
    '("ring_simplify @{term+}" . ("9i" . 776))
    '("field" . ("9j" . 777))
    '("field_simplify @{term+}" . ("9j" . 778))
    '("field_simplify_eq" . ("9j" . 779))
    '("fourier" . ("9k" . 780))
    '("cycle @{num}" . ("9m" . 781))
    '("swap @{num} @{num}" . ("9n" . 782))
    '("revgoals" . ("9o" . 783))
    '("shelve" . ("9p" . 784))
    '("shelve_unifiable" . ("9p" . 785))
    '("Unshelve." . ("9q" . 786))
    '("give_up" . ("9r" . 787))
    '("do @{num} @{expr}" . ("9w" . 788))
    '("repeat @{expr}" . ("9w" . 789))
    '("try @{expr}" . ("9w" . 790))
    '("progress @{expr}" . ("9w" . 791))
    '("tryif @{expr} then @{expr} else @{expr}" . ("9w" . 794))
    '("once @{expr}" . ("9w" . 795))
    '("exactly_once @{expr}" . ("9w" . 796))
    '("solve [@{expr|+}]" . ("9w" . 798))
    '("idtac" . ("9w" . 800))
    '("idtac @{message_token+}" . ("9w" . 801))
    '("fail" . ("9w" . 802))
    '("fail @{n}" . ("9w" . 803))
    '("fail @{message_token+}" . ("9w" . 804))
    '("fail @{n} @{message_token+}" . ("9w" . 805))
    '("gfail" . ("9w" . 806))
    '("gfail @{message_token+}" . ("9w" . 807))
    '("gfail @{n} @{message_token+}" . ("9w" . 808))
    '("timeout @{num} @{expr}" . ("9w" . 810))
    '("time @{string} @{expr}" . ("9w" . 811))
    '("@{qualid} @{tacarg+}" . ("9w" . 812))
    '("fun @{ident+} => @{expr}" . ("9w" . 813))
    '("context @{ident} [@{cpattern}]" . ("9w" . 816))
    '("appcontext @{ident} [@{cpattern}]" . ("9w" . 817))
    '("context @{ident} [@{expr}]" . ("9w" . 819))
    '("fresh @{component+}" . ("9w" . 821))
    '("eval @{redexpr} in @{term}" . ("9w" . 822))
    '("type of @{term}" . ("9w" . 823))
    '("uconstr : @{term}" . ("9w" . 824))
    '("type_term @{term}" . ("9w" . 825))
    '("guard @{test}" . ("9w" . 826))
    '("abstract @{expr}" . ("9w" . 828))
    '("Qed exporting." . ("9w" . 829))
    '("Qed exporting @{ident,+}." . ("9w" . 830))
    '("abstract @{expr} using @{ident}" . ("9w" . 831))
    '("Print Ltac @{qualid}." . ("9z" . 833))
    '("Info @{num} @{expr}." . ("a1" . 834))
    '("Set Info Level @{num}." . ("a1" . 835))
    '("Test Info Level @{num}." . ("a1" . 835))
    '("Unset Info Level @{num}." . ("a1" . 836))
    '("Set Ltac Debug." . ("a2" . 837))
    '("Test Ltac Debug." . ("a2" . 837))
    '("Unset Ltac Debug." . ("a2" . 838))
    '("specialize_eqs" . ("a5" . 839))
    '("Print Grammar pattern." . ("ba" . 841))
    '("Open Scope @{scope}." . ("bm" . 842))
    '("Close Scope @{scope}." . ("bm" . 843))
    '("Local Open Scope @{scope}." . ("bm" . 844))
    '("Local Close Scope @{scope}." . ("bm" . 845))
    '("Global Open Scope @{scope}." . ("bm" . 846))
    '("Global Close Scope @{scope}." . ("bm" . 847))
    '("Arguments @{qualid} @{name&} %@{scope&}." . ("bn" . 848))
    '("Arguments @{qualid} : clear scopes." . ("bn" . 849))
    '("Global Arguments @{qualid} @{name&} %@{scope&}." . ("bn" . 850))
    '("Local Arguments @{qualid} @{name&} %@{scope&}." . ("bn" . 851))
    '("Bind Scope @{scope} with @{qualid}." . ("bn" . 852))
    '("Print Scopes." . ("bp" . 866))
    '("Print Scope @{scope}." . ("bp" . 867))
    '("type_scope" . ("bp" . 868))
    '("nat_scope" . ("bp" . 869))
    '("N_scope" . ("bp" . 870))
    '("Z_scope" . ("bp" . 871))
    '("positive_scope" . ("bp" . 872))
    '("Q_scope" . ("bp" . 873))
    '("Qc_scope" . ("bp" . 874))
    '("real_scope" . ("bp" . 875))
    '("bool_scope" . ("bp" . 876))
    '("list_scope" . ("bp" . 877))
    '("core_scope" . ("bp" . 878))
    '("string_scope" . ("bp" . 879))
    '("char_scope" . ("bp" . 880))
    '("Print Visibility." . ("bq" . 871))
    '("Print Visibility @{scope}." . ("bq" . 872))
    '("Notation @{ident} := @{term}." . ("br" . 872))
    '("Notation @{ident} := @{term} (only parsing)." . ("br" . 872))
    '("Notation @{ident} @{ident&} @{ident&} := @{term}." . ("br" . 872))
    '("Notation @{ident} @{ident&} @{ident&} := @{term} (only parsing)." . ("br" . 872))
    '("Local Notation @{ident} := @{term}." . ("br" . 872))
    '("Local Notation @{ident} := @{term} (only parsing)." . ("br" . 872))
    '("Local Notation @{ident} @{ident&} @{ident&} := @{term}." . ("br" . 872))
    '("Local Notation @{ident} @{ident&} @{ident&} := @{term} (only parsing)." . ("br" . 872))
    '("Tactic Notation @{tactic_level} := @{tactic}." . ("bs" . 873))
    '("Tactic Notation @{tactic_level} @{prod_item+} := @{tactic}." . ("bs" . 873))
    '("Print Grammar tactic." . ("bs" . 874))
    '("Context @{binder+}." . ("eh" . 886))
    '("Typeclasses Transparent @{ident+}." . ("ei" . 887))
    '("Typeclasses Opaque @{ident+}." . ("ei" . 888))
    '("Typeclasses eauto :=." . ("ej" . 889))
    '("Typeclasses eauto := @{dfs|bfs} @{depth}." . ("ej" . 889))
    '("Typeclasses eauto := debug." . ("ej" . 889))
    '("Typeclasses eauto := debug @{dfs|bfs} @{depth}." . ("ej" . 889))
    '("Set Refine Instance Mode." . ("ek" . 890))
    '("Unset Refine Instance Mode." . ("ek" . 890))
    '("Test Refine Instance Mode." . ("ek" . 890))
    '("psatz" . ("ey" . 899))
    '("lra" . ("f1" . 900))
    '("lia" . ("f5" . 901))
    '("nia" . ("f8" . 902))
    '("Extraction @{qualid}." . ("fa" . 903))
    '("Extraction \"@{file}\" @{qualid+}." . ("fa" . 905))
    '("Extraction Library @{ident}." . ("fa" . 906))
    '("Recursive Extraction Library @{ident}." . ("fa" . 907))
    '("Separate Extraction @{qualid+}." . ("fa" . 908))
    '("Extraction Language Ocaml." . ("fc" . 909))
    '("Extraction Language Haskell." . ("fc" . 910))
    '("Extraction Language Scheme." . ("fc" . 911))
    '("Set Extraction Optimize." . ("fd" . 912))
    '("Test Extraction Optimize." . ("fd" . 912))
    '("Unset Extraction Optimize." . ("fd" . 913))
    '("Set Extraction Conservative Types." . ("fd" . 914))
    '("Test Extraction Conservative Types." . ("fd" . 914))
    '("Unset Extraction Conservative Types." . ("fd" . 915))
    '("Set Extraction KeepSingleton." . ("fd" . 916))
    '("Test Extraction KeepSingleton." . ("fd" . 916))
    '("Unset Extraction KeepSingleton." . ("fd" . 917))
    '("Set Extraction AutoInline." . ("fd" . 918))
    '("Test Extraction AutoInline." . ("fd" . 918))
    '("Unset Extraction AutoInline." . ("fd" . 919))
    '("Extraction Inline @{qualid+}." . ("fd" . 920))
    '("Extraction NoInline @{qualid+}." . ("fd" . 921))
    '("Print Extraction Inline." . ("fd" . 922))
    '("Reset Extraction Inline." . ("fd" . 923))
    '("Extraction Implicit @{qualid} [@{ident+}]." . ("fe" . 924))
    '("Extract Constant @{qualid} => \"@{string}\"." . ("ff" . 925))
    '("Extract Inlined Constant @{qualid} => \"@{string}\"." . ("ff" . 926))
    '("Extract Constant @{qualid} \"@{string+}\" => \"@{string}\"." . ("ff" . 927))
    '("Extract Inductive @{qualid} => \"@{string}\" [\"@{string+}\"] @{optstring}." . ("ff" . 928))
    '("Extraction Blacklist @{ident+}." . ("fg" . 929))
    '("Print Extraction Blacklist." . ("fg" . 930))
    '("Reset Extraction Blacklist." . ("fg" . 931))
    '("ring_simplify" . ("g0" . 935))
    '("ring [@{term+}]" . ("g0" . 936))
    '("ring_simplify [@{term+}] @{t+} in @{ident}" . ("g0" . 937))
    '("Add Ring @{name} : @{ring} (@{mod,+})." . ("g1" . 942))
    '("field [@{term+}]" . ("g3" . 947))
    '("field_simplify" . ("g3" . 948))
    '("field_simplify [@{term+}]" . ("g3" . 949))
    '("field_simplify [@{term+}] @{term+}" . ("g3" . 950))
    '("field_simplify in @{hyp}" . ("g3" . 951))
    '("field_simplify [@{term+}] in @{hyp}" . ("g3" . 952))
    '("field_simplify [@{term+}] @{term+} in @{hyp}" . ("g3" . 953))
    '("field_simplify_eq [@{term+}]" . ("g3" . 955))
    '("field_simplify_eq in @{hyp}" . ("g3" . 956))
    '("field_simplify_eq [@{term+}] in @{hyp}" . ("g3" . 957))
    '("Add Field @{name} : @{field} (@{mod,+})." . ("g4" . 958))
    '("nsatz" . ("g9" . 959))
    '("nsatz with radicalmax:=@{num}%N strategy:=@{num}%Z parameters:=@{list of vars} variables:=@{list of vars}" . ("g9" . 960))
    '("setoid_reflexivity" . ("gl" . 961))
    '("setoid_symmetry" . ("gl" . 962))
    '("setoid_symmetry in @{ident}" . ("gl" . 962))
    '("setoid_transitivity" . ("gl" . 963))
    '("setoid_rewrite @{term}" . ("gl" . 964))
    '("setoid_rewrite @{term} in @{ident}" . ("gl" . 964))
    '("setoid_rewrite <- @{term}" . ("gl" . 965))
    '("setoid_rewrite <- @{term} in @{ident}" . ("gl" . 965))
    '("setoid_rewrite <- @{term} at @{occs}" . ("gl" . 966))
    '("setoid_rewrite <- @{term} at @{occs} in @{ident}" . ("gl" . 966))
    '("setoid_rewrite @{term} at @{occs}" . ("gl" . 967))
    '("setoid_rewrite @{term} at @{occs} in @{ident}" . ("gl" . 967))
    '("setoid_rewrite @{orientation} @{term}" . ("gl" . 967))
    '("setoid_rewrite @{orientation} @{term} in @{ident}" . ("gl" . 967))
    '("setoid_rewrite @{orientation} @{term} at @{occs}" . ("gl" . 967))
    '("setoid_rewrite @{orientation} @{term} at @{occs} in @{ident}" . ("gl" . 967))
    '("setoid_replace @{term} with @{term}" . ("gl" . 968))
    '("setoid_replace @{term} with @{term} by @{tactic}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} using relation @{term}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} using relation @{term} by @{tactic}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} in @{ident}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} in @{ident} by @{tactic}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} in @{ident} using relation @{term}" . ("gl" . 969))
    '("setoid_replace @{term} with @{term} in @{ident} using relation @{term} by @{tactic}" . ("gl" . 969))
    '("Print Instances @{Reflexive|Symmetric|Transitive|Equivalence|PreOrder|PER|Proper}." . ("gm" . 970))
    '("rewrite_strat @{s}" . ("gu" . 971))
    '("rewrite_strat @{s} in @{ident}" . ("gu" . 971))))

(defconst company-coq-errors
  (list
    '("@{ident} already exists" . ("10" . 0))
    '("The term @{term} has type @{type} while it is expected to have type @{type}" . ("11" . 3))
    '("Non strictly positive occurrence of @{ident} in @{type}" . ("12" . 5))
    '("The conclusion of @{type} is not valid; it must be built from @{ident}" . ("12" . 6))
    '("The @{num}th argument of @{ident} must be @{ident}’ in @{type}" . ("12" . 7))
    '("The term @{form} has type @{hole} which should be Set, Prop or Type" . ("14" . 10))
    '("Records declared with the keyword Record or Structure cannot be recursive." . ("16" . 19))
    '("Cannot handle mutually (co)inductive records." . ("16" . 20))
    '("The recursive argument must be specified" . ("1d" . 42))
    '("No argument name @{ident}" . ("1d" . 43))
    '("Cannot use mutual definition with well-founded recursion or measure" . ("1d" . 44))
    '("Cannot define graph for @{ident}@{hole}" . ("1d" . 45))
    '("Cannot define principle(s) for @{ident}@{hole}" . ("1d" . 46))
    '("Cannot build functional inversion principle" . ("1d" . 47))
    '("This is not the last opened section" . ("1g" . 48))
    '("Cannot infer a term for this placeholder" . ("1o" . 49))
    '("No such label @{ident}" . ("2c" . 107))
    '("Signature components for label @{ident} do not match" . ("2c" . 108))
    '("This is not the last opened module" . ("2c" . 109))
    '("This is not the last opened module type" . ("2c" . 121))
    '("@{qualid} is not a module" . ("2c" . 129))
    '("Universe inconsistency" . ("35" . 125))
    '("not a defined object" . ("3t" . 127))
    '("The reference @{qualid} was not found in the current environment" . ("4a" . 160))
    '("Module/section @{module} not found" . ("4b" . 172))
    '("Can’t find file @{ident} on loadpath" . ("4g" . 192))
    '("Cannot load @{qualid}: no physical path bound to @{dirpath}" . ("4i" . 198))
    '("Cannot find library foo in loadpath" . ("4i" . 199))
    '("Compiled library @{ident}.vo makes inconsistent assumptions over library @{qualid}" . ("4i" . 200))
    '("Bad magic number" . ("4i" . 201))
    '("The file @{ident}.vo contains library @{dirpath} and not library @{dirpath}’" . ("4i" . 202))
    '("Require is not allowed inside a module or a module type" . ("4i" . 203))
    '("File not found on loadpath : \"@{string}\"" . ("4k" . 207))
    '("Loading of ML object file forbidden in a native Coq" . ("4k" . 208))
    '("no such entry" . ("4z" . 226))
    '("Invalid backtrack" . ("50" . 229))
    '("No focused proof" . ("5u" . 262))
    '("Attempt to save an incomplete proof" . ("5x" . 265))
    '("No focused proof (No proof-editing in progress)" . ("61" . 291))
    '("No focused proof to restart" . ("66" . 299))
    '("This proof is focused, but cannot be unfocused this way" . ("6a" . 304))
    '("Wrong bullet @{bullet}1 : Current bullet @{bullet}2 is not finished." . ("6b" . 305))
    '("Wrong bullet @{bullet}1 : Bullet @{bullet}2 is mandatory here." . ("6b" . 306))
    '("No such goal. Focus next goal with bullet @{bullet}." . ("6b" . 307))
    '("No such goal. Try unfocusing with \"}\"." . ("6b" . 308))
    '("No such goal" . ("6d" . 311))
    '("No such binder" . ("6q" . 328))
    '("Not the right number of missing arguments" . ("6q" . 329))
    '("Not an exact proof" . ("6t" . 331))
    '("No such assumption" . ("6u" . 334))
    '("invalid argument" . ("6v" . 337))
    '("Impossible to unify @{hole} with @{hole}" . ("6w" . 340))
    '("Unable to find an instance for the variables @{ident+}" . ("6w" . 341))
    '("Statement without assumptions" . ("6x" . 350))
    '("Unable to apply" . ("6x" . 351))
    '("Not an inductive product" . ("6y" . 360))
    '("Not enough constructors" . ("6y" . 361))
    '("Not an inductive goal with 1 constructor" . ("6y" . 365))
    '("Not an inductive goal with 2 constructors" . ("6y" . 371))
    '("No product even after head-reduction" . ("70" . 381))
    '("@{ident} is already used" . ("70" . 382))
    '("name @{ident} is already used" . ("70" . 385))
    '("No such hypothesis in current goal" . ("70" . 388))
    '("No such hypothesis" . ("70" . 395))
    '("@{ident} is used in the conclusion" . ("73" . 403))
    '("@{ident} is used in the hypothesis @{ident}’" . ("73" . 404))
    '("@{ident} is not a local definition" . ("73" . 407))
    '("Cannot move @{ident} after @{ident}: it occurs in @{ident}" . ("75" . 420))
    '("Cannot move @{ident} after @{ident}: it depends on @{ident}" . ("75" . 421))
    '("The variable @{ident} is already defined" . ("77" . 427))
    '("Not a proposition or a type" . ("7a" . 443))
    '("Proof is not complete" . ("7a" . 446))
    '("Variable @{ident} is already declared" . ("7a" . 450))
    '("@{ident} is used in hypothesis @{ident}’" . ("7a" . 461))
    '("@{ident} is used in conclusion" . ("7a" . 462))
    '("Cannot find induction information on @{qualid}" . ("7o" . 529))
    '("Not the right number of induction arguments" . ("7o" . 530))
    '("No primitive equality found" . ("7p" . 533))
    '("Not a discriminable equality" . ("7p" . 534))
    '("No discriminable equalities" . ("7p" . 540))
    '("Not a projectable equality but a discriminable one" . ("7r" . 542))
    '("Nothing to do, it is an equality between convertible terms" . ("7r" . 543))
    '("Not a primitive equality" . ("7r" . 544))
    '("goal does not satisfy the expected preconditions" . ("7r" . 550))
    '("The term provided does not end with an equation" . ("7w" . 585))
    '("Tactic generated a subgoal identical to the original goal" . ("7w" . 586))
    '("terms do not have convertible types" . ("7x" . 595))
    '("Not convertible" . ("80" . 615))
    '("Not reducible" . ("83" . 636))
    '("does not denote an evaluable constant" . ("86" . 649))
    '("Bound head variable" . ("8h" . 688))
    '("cannot be used as a hint" . ("8h" . 689))
    '("is not an inductive type" . ("8h" . 696))
    '("not declared" . ("8h" . 697))
    '("I don’t know how to handle dependent equality" . ("8t" . 733))
    '("Goal is solvable by congruence but some arguments are missing. Try \"congruence with @{hole}\", replacing metavariables by arbitrary terms." . ("8t" . 734))
    '("Not equal" . ("8v" . 736))
    '("Not unifiable" . ("8w" . 738))
    '("Not an evar" . ("8x" . 741))
    '("No evars" . ("8y" . 743))
    '("Not a variable or hypothesis" . ("8z" . 745))
    '("The conclusion is not a substitutive equation" . ("92" . 748))
    '("Hypothesis @{ident} must contain at least one Function" . ("9b" . 764))
    '("Cannot find inversion information for hypothesis @{ident}" . ("9b" . 765))
    '("quote: not a simple fixpoint" . ("9c" . 769))
    '("Failed to progress" . ("9w" . 792))
    '("No applicable tactic" . ("9w" . 793))
    '("This tactic has more than one success" . ("9w" . 797))
    '("Cannot solve the goal" . ("9w" . 799))
    '("Tactic Failure @{message} (level @{n})" . ("9w" . 809))
    '("No matching clauses for match" . ("9w" . 814))
    '("Argument of match does not evaluate to a term" . ("9w" . 815))
    '("No matching clauses for match goal" . ("9w" . 818))
    '("not a context variable" . ("9w" . 820))
    '("Condition not satisfied" . ("9w" . 827))
    '("Non exhaustive pattern-matching" . ("de" . 875))
    '("is already a coercion" . ("dm" . 877))
    '("Funclass cannot be a source class" . ("dm" . 878))
    '("Sortclass cannot be a source class" . ("dm" . 879))
    '("is not a function" . ("dm" . 880))
    '("Cannot find the source class of @{qualid}" . ("dm" . 881))
    '("Cannot recognize @{class} as a source class of @{qualid}" . ("dm" . 882))
    '("does not respect the uniform inheritance condition" . ("dm" . 883))
    '("Found target class @{class} instead of @{class}" . ("dm" . 884))
    '("must be a transparent constant" . ("dn" . 885))
    '("omega can’t solve this system" . ("eo" . 891))
    '("omega: Not a quantifier-free goal" . ("eo" . 892))
    '("omega: Unrecognized predicate or connective: @{ident}" . ("eo" . 893))
    '("omega: Unrecognized atomic proposition: @{prop}" . ("eo" . 894))
    '("omega: Can’t solve a goal with proposition variables" . ("eo" . 895))
    '("omega: Unrecognized proposition" . ("eo" . 896))
    '("omega: Can’t solve a goal with non-linear products" . ("eo" . 897))
    '("omega: Can’t solve a goal with equality on @{type}" . ("eo" . 898))
    '("In environment @{hole} the term: @{term} does not have type @{term}" . ("fp" . 933))
    '("not a valid ring equation" . ("g0" . 938))
    '("arguments of ring_simplify do not have all the same type" . ("g0" . 939))
    '("cannot find a declared ring structure over term" . ("g0" . 940))
    '("cannot find a declared ring structure for equality term" . ("g0" . 941))
    '("bad ring structure" . ("g1" . 943))
    '("bad lemma for decidability of equality" . ("g1" . 944))
    '("ring @{operation} should be declared as a morphism" . ("g1" . 945))
    '("Nothing to rewrite" . ("gu" . 972))
    '("No progress made" . ("gu" . 973))
    '("Unable to satisfy the rewriting constraints" . ("gu" . 974))
    '("Undeclared universe @{ident}" . ("h4" . 976))))

(provide 'company-coq-abbrev)
;;; company-coq-abbrev.el ends here
