name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # build at 00:05 every Sunday
    - cron: '5 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - 30.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install dependencies
      run: sudo apt install -y aspell aspell-en

    - name: Print emacs version
      run: emacs --version

    - name: Run tests
      run: make test